pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCESS_KEY_ID = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }
    
    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main', credentialsId: 'Git', url: 'https://github.com/Sourabh10tiwari/AWS-Backup'
            }
        }

        stage('Terraform Init') {
            steps {
                dir('terraform'){
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('terraform'){
                    sh 'terraform plan -out=tfplan'
                }
            }
        }

	stage('Manual Approval') {
    		steps {
        		script {
            			input message: "Approve Terraform Apply?", ok: "Yes"
        		}
    		}
	}

        stage('Terraform Apply') {
            steps {
                dir('terraform'){
			sh 'terraform apply -auto-approve tfplan'
                }
            }
        }
    }

    post {
        success {
            echo 'Terraform Apply completed successfully.'
        }
        failure {
            echo 'Terraform Apply failed.'
        }
    }
}
